### ISSUE TITLE
 Error putting IAM role policy <policy_name> MalformedPolicyDocument: Policy statement must contain resources.

### ISSUE THREAD

**Issue by wesleywh** [trussworks/terraform-aws-s3-anti-virus#28]
│ Error: Error putting IAM role policy <redacted>: MalformedPolicyDocument: Policy statement must contain resources.
│       status code: 400, request id: a0c0944c-10ce-4bc1-a4d5-b8ad743a51e8
│ 
│   with module.s3_anti_virus.aws_iam_role_policy.main_scan,
│   on .terraform/modules/s3_anti_virus/anti-virus-scan.tf line 116, in resource "aws_iam_role_policy" "main_scan":
│  116: resource "aws_iam_role_policy" "main_scan" {

You have issues in your terraform. There are also issues with potentially lacking permissions when supplying `av_scan_buckets` there isn't any documentation on what permissions are required to deploy this either. So I'm just going to extract out the resources from the module and modify it until I get it to work.

Just thought I would pass this information onto you so you can fix your malformed policy and permission issues with this module.

**Comment by rpdelaney** [comment]
Hi, thanks for opening this issue. I need a little more information to diagnose this.

Can you tell me which version of the module you are using? Scanning the tip of main, it looks like resources are being defined in each statement of that policy. Any code you are using to call the module could help run this down also.

By the way, you can make code snippets you post on github more readable by using [fenced code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

Thanks again.
