### ISSUE TITLE
No delete permissions

### ISSUE THREAD

**Issue by garettmd** [trussworks/terraform-aws-s3-anti-virus#35]
I noticed after trying to run this that delete permissions were missing from the policy document resource. This means that if you have `input_av_delete_infected_files` set to `true`, the lambda function will error out as it doesn't have access to delete files. I added the permissions and was able to get it to work.

Am I just using the module incorrectly? If not, I can submit a PR with the changes

**Comment by liranbenabu1** [comment]
Hi, I fixed it in the PR https://github.com/trussworks/terraform-aws-s3-anti-virus/pull/32. 
waiting for someone to approve it merge the branch

**Comment by lliranbabi** [comment]
@garettmd - merged

**Comment by liranbenabu1** [comment]
@garettmd - merged, you can use the latest version 3.2.2 with the fix :)
